[context.production.environment]
  HUGO_VERSION = "0.69.2"

  [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    #'./build-dir/path-to/file.html',
    # By Glob pattern
    '**/page/**'
  ]
